# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@fastify/ajv-compiler-3.2.0" = {
      name = "_at_fastify_slash_ajv-compiler";
      packageName = "@fastify/ajv-compiler";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/ajv-compiler/-/ajv-compiler-3.2.0.tgz";
        sha512 = "JrqgKmZoh1AJojDZk699DupQ9+tz5gSy7/w+5DrkXy5whM5IcqdV3SjG5qnOqgVJT1nPtUMDY0xYus2j6vwJiw==";
      };
    };
    "@fastify/deepmerge-1.1.0" = {
      name = "_at_fastify_slash_deepmerge";
      packageName = "@fastify/deepmerge";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/deepmerge/-/deepmerge-1.1.0.tgz";
        sha512 = "E8Hfdvs1bG6u0N4vN5Nty6JONUfTdOciyD5rn8KnEsLKIenvOVcr210BQR9t34PRkNyjqnMLGk3e0BsaxRdL+g==";
      };
    };
    "@fastify/error-3.0.0" = {
      name = "_at_fastify_slash_error";
      packageName = "@fastify/error";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/error/-/error-3.0.0.tgz";
        sha512 = "dPRyT40GiHRzSCll3/Jn2nPe25+E1VXc9tDwRAIKwFCxd5Np5wzgz1tmooWG3sV0qKgrBibihVoCna2ru4SEFg==";
      };
    };
    "@fastify/fast-json-stringify-compiler-4.1.0" = {
      name = "_at_fastify_slash_fast-json-stringify-compiler";
      packageName = "@fastify/fast-json-stringify-compiler";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/fast-json-stringify-compiler/-/fast-json-stringify-compiler-4.1.0.tgz";
        sha512 = "cTKBV2J9+u6VaKDhX7HepSfPSzw+F+TSd+k0wzifj4rG+4E5PjSFJCk19P8R6tr/72cuzgGd+mbB3jFT6lvAgw==";
      };
    };
    "@tsconfig/node16-1.0.3" = {
      name = "_at_tsconfig_slash_node16";
      packageName = "@tsconfig/node16";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node16/-/node16-1.0.3.tgz";
        sha512 = "yOlFc+7UtL/89t2ZhjPvvB/DeAr3r+Dq58IgzsFkOAvVC6NMJXmCGjbptdXdR9qsX7pKcTL+s87FtYREi2dEEQ==";
      };
    };
    "@tsconfig/node16-strictest-1.0.3" = {
      name = "_at_tsconfig_slash_node16-strictest";
      packageName = "@tsconfig/node16-strictest";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node16-strictest/-/node16-strictest-1.0.3.tgz";
        sha512 = "sY7TxE3BzAdsCuKqGWOTtAoPe4tPD0xlPWfjinJvrBvCulyALVSwvIoo7WMcX8O/WyMFzn9rQObA43mAogQ8MQ==";
      };
    };
    "@types/node-18.7.14" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "18.7.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-18.7.14.tgz";
        sha512 = "6bbDaETVi8oyIARulOE9qF1/Qdi/23z6emrUh0fNJRUmjznqrixD4MpGDdgOFk5Xb0m2H6Xu42JGdvAxaJR/wA==";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "abstract-logging-2.0.1" = {
      name = "abstract-logging";
      packageName = "abstract-logging";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abstract-logging/-/abstract-logging-2.0.1.tgz";
        sha512 = "2BjRTZxTPvheOvGbBslFSYOUkr+SjPtOnrLP33f+VIWLzezQpZcqVg7ja3L4dBXmzzgwT+a029jRx5PCi3JuiA==";
      };
    };
    "ajv-8.11.0" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.11.0.tgz";
        sha512 = "wGgprdCvMalC0BztXvitD2hC04YffAvtsUn93JbGXYLAtCUO4xd17mCCZQxUOItiBwZvJScWo8NIvQMQ71rdpg==";
      };
    };
    "ajv-formats-2.1.1" = {
      name = "ajv-formats";
      packageName = "ajv-formats";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-formats/-/ajv-formats-2.1.1.tgz";
        sha512 = "Wx0Kx52hxE7C18hkMEggYlEifqWZtYaRgouJor+WMdPnQyEK13vgEWyVNup7SoeeoLMsr4kf5h6dOW11I15MUA==";
      };
    };
    "archy-1.0.0" = {
      name = "archy";
      packageName = "archy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archy/-/archy-1.0.0.tgz";
        sha512 = "Xg+9RwCg/0p32teKdGMPTPnVXKD0w3DfHnFTficozsAgsvq2XenPJq/MYpzzQ/v8zrOyJn6Ds39VA4JIDwFfqw==";
      };
    };
    "atomic-sleep-1.0.0" = {
      name = "atomic-sleep";
      packageName = "atomic-sleep";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/atomic-sleep/-/atomic-sleep-1.0.0.tgz";
        sha512 = "kNOjDqAh7px0XWNI+4QbzoiR/nTkHAWNud2uvnJquD1/x5a7EQZMJT0AczqK0Qn67oY/TTQ1LbUKajZpp3I9tQ==";
      };
    };
    "avvio-8.2.0" = {
      name = "avvio";
      packageName = "avvio";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/avvio/-/avvio-8.2.0.tgz";
        sha512 = "bbCQdg7bpEv6kGH41RO/3B2/GMMmJSo2iBK+X8AWN9mujtfUipMDfIjsgHCfpnKqoGEQrrmCDKSa5OQ19+fDmg==";
      };
    };
    "cookie-0.5.0" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.5.0.tgz";
        sha512 = "YZ3GUyn/o8gfKJlnlX7g7xq4gyO6OSuhGPKaaGssGB2qgDUS0gPgtTvoyZLTt9Ab6dC4hfc9dV5arkvc/OCmrw==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stringify-5.2.0" = {
      name = "fast-json-stringify";
      packageName = "fast-json-stringify";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stringify/-/fast-json-stringify-5.2.0.tgz";
        sha512 = "u5jtrcAK9RINW15iuDKnsuuhqmqre4AmDMp3crRTjUMdAuHMpQUt3IfoMm5wlJm59b74PcajqOl3SjgnC5FPmw==";
      };
    };
    "fast-redact-3.1.2" = {
      name = "fast-redact";
      packageName = "fast-redact";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-redact/-/fast-redact-3.1.2.tgz";
        sha512 = "+0em+Iya9fKGfEQGcd62Yv6onjBmmhV1uh86XVfOU8VwAe6kaFdQCWI9s0/Nnugx5Vd9tdbZ7e6gE2tR9dzXdw==";
      };
    };
    "fast-uri-2.1.0" = {
      name = "fast-uri";
      packageName = "fast-uri";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-uri/-/fast-uri-2.1.0.tgz";
        sha512 = "qKRta6N7BWEFVlyonVY/V+BMLgFqktCUV0QjT259ekAIlbVrMaFnFLxJ4s/JPl4tou56S1BzPufI60bLe29fHA==";
      };
    };
    "fastify-4.5.3" = {
      name = "fastify";
      packageName = "fastify";
      version = "4.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastify/-/fastify-4.5.3.tgz";
        sha512 = "Q8Zvkmg7GnioMCDX1jT2Q7iRqjywlnDZ1735D2Ipf7ashCM/3/bqPKv2Jo1ZF2iDExct2eP1C/tdhcj0GG/OuQ==";
      };
    };
    "fastq-1.13.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.13.0.tgz";
        sha512 = "YpkpUnK8od0o1hmeSc7UUs/eB/vIPWJYjKck2QKIzAf71Vm1AAQ3EbuZB3g2JIy+pg+ERD0vqI79KyZiB2e2Nw==";
      };
    };
    "find-my-way-7.0.1" = {
      name = "find-my-way";
      packageName = "find-my-way";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-my-way/-/find-my-way-7.0.1.tgz";
        sha512 = "w05SaOPg54KqBof/RDA+75n1R48V7ZZNPL3nR17jJJs5dgZpR3ivfrMWOyx7BVFQgCLhYRG05hfgFCohYvSUXA==";
      };
    };
    "forwarded-0.2.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz";
        sha512 = "buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "light-my-request-5.5.1" = {
      name = "light-my-request";
      packageName = "light-my-request";
      version = "5.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/light-my-request/-/light-my-request-5.5.1.tgz";
        sha512 = "Zd4oZjF7axSyc5rYQsbB0qsgY4LFFviZSbEywxf7Vi5UE3y3c7tYF/GeheQjBNYY+pQ55BF8UGGJTjneoxOS1w==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "on-exit-leak-free-2.1.0" = {
      name = "on-exit-leak-free";
      packageName = "on-exit-leak-free";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-exit-leak-free/-/on-exit-leak-free-2.1.0.tgz";
        sha512 = "VuCaZZAjReZ3vUwgOB8LxAosIurDiAW0s13rI1YwmaP++jvcxP77AWoQvenZebpCA2m8WC1/EosPYPMjnRAp/w==";
      };
    };
    "pino-8.4.2" = {
      name = "pino";
      packageName = "pino";
      version = "8.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino/-/pino-8.4.2.tgz";
        sha512 = "PlXDeGhJZfAuVay+wtlS02s5j8uisQveZExYdAm9MwwxUQSz9R7Q78XtjM2tTa4sa5KJmygimZjZxXXuHgV6ew==";
      };
    };
    "pino-abstract-transport-1.0.0" = {
      name = "pino-abstract-transport";
      packageName = "pino-abstract-transport";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-abstract-transport/-/pino-abstract-transport-1.0.0.tgz";
        sha512 = "c7vo5OpW4wIS42hUVcT5REsL8ZljsUfBjqV/e2sFxmFEFZiq1XLUp5EYLtuDH6PEHq9W1egWqRbnLUP5FuZmOA==";
      };
    };
    "pino-std-serializers-6.0.0" = {
      name = "pino-std-serializers";
      packageName = "pino-std-serializers";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-std-serializers/-/pino-std-serializers-6.0.0.tgz";
        sha512 = "mMMOwSKrmyl+Y12Ri2xhH1lbzQxwwpuru9VjyJpgFIH4asSj88F2csdMwN6+M5g1Ll4rmsYghHLQJw81tgZ7LQ==";
      };
    };
    "process-warning-2.0.0" = {
      name = "process-warning";
      packageName = "process-warning";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-warning/-/process-warning-2.0.0.tgz";
        sha512 = "+MmoAXoUX+VTHAlwns0h+kFUWFs/3FZy+ZuchkgjyOu3oioLAo2LB5aCfKPh2+P9O18i3m43tUEv3YqttSy0Ww==";
      };
    };
    "proxy-addr-2.0.7" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz";
        sha512 = "llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "quick-format-unescaped-4.0.4" = {
      name = "quick-format-unescaped";
      packageName = "quick-format-unescaped";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-format-unescaped/-/quick-format-unescaped-4.0.4.tgz";
        sha512 = "tYC1Q1hgyRuHgloV/YXs2w15unPVh8qfu/qCTfhTYamaw7fyhumKa2yGpdSo87vY32rIclj+4fWYQXUMs9EHvg==";
      };
    };
    "readable-stream-4.1.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-4.1.0.tgz";
        sha512 = "sVisi3+P2lJ2t0BPbpK629j8wRW06yKGJUcaLAGXPAUhyUxVJm7VsCTit1PFgT4JHUDMrGNR+ZjSKpzGaRF3zw==";
      };
    };
    "real-require-0.2.0" = {
      name = "real-require";
      packageName = "real-require";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/real-require/-/real-require-0.2.0.tgz";
        sha512 = "57frrGM/OCTLqLOAh0mhVA9VBMHd+9U7Zb2THMGdBUoZVOtGbJzjxsYGDJ3A9AYYCP4hn6y1TVbaOfzWtm5GFg==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "ret-0.2.2" = {
      name = "ret";
      packageName = "ret";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.2.2.tgz";
        sha512 = "M0b3YWQs7R3Z917WRQy1HHA7Ba7D8hvZg6UE5mLykJxQVE2ju0IXbGlaHPPlkY+WN7wFP+wUMXmBFA0aV6vYGQ==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rfdc-1.3.0" = {
      name = "rfdc";
      packageName = "rfdc";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rfdc/-/rfdc-1.3.0.tgz";
        sha512 = "V2hovdzFbOi77/WajaSMXk2OLm+xNIeQdMMuB7icj7bk6zi2F8GGAxigcnDFpJHbNyNcgyJDiP+8nOrY5cZGrA==";
      };
    };
    "safe-regex2-2.0.0" = {
      name = "safe-regex2";
      packageName = "safe-regex2";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex2/-/safe-regex2-2.0.0.tgz";
        sha512 = "PaUSFsUaNNuKwkBijoAPHAK6/eM6VirvyPWlZ7BAQy4D+hCvh4B6lIG+nPdhbFfIbP+gTGBcrdsOaUs0F+ZBOQ==";
      };
    };
    "safe-stable-stringify-2.3.1" = {
      name = "safe-stable-stringify";
      packageName = "safe-stable-stringify";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-stable-stringify/-/safe-stable-stringify-2.3.1.tgz";
        sha512 = "kYBSfT+troD9cDA85VDnHZ1rpHC50O0g1e6WlGHVCz/g+JS+9WKLj+XwFYyR8UbrZN8ll9HUpDAAddY58MGisg==";
      };
    };
    "secure-json-parse-2.5.0" = {
      name = "secure-json-parse";
      packageName = "secure-json-parse";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/secure-json-parse/-/secure-json-parse-2.5.0.tgz";
        sha512 = "ZQruFgZnIWH+WyO9t5rWt4ZEGqCKPwhiw+YbzTwpmT9elgLrLcfuyUiSnwwjUiVy9r4VM3urtbNF1xmEh9IL2w==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "set-cookie-parser-2.5.1" = {
      name = "set-cookie-parser";
      packageName = "set-cookie-parser";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-cookie-parser/-/set-cookie-parser-2.5.1.tgz";
        sha512 = "1jeBGaKNGdEq4FgIrORu/N570dwoPYio8lSoYLWmX7sQ//0JY08Xh9o5pBcgmHQ/MbsYp/aZnOe1s1lIsbLprQ==";
      };
    };
    "sonic-boom-3.2.0" = {
      name = "sonic-boom";
      packageName = "sonic-boom";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sonic-boom/-/sonic-boom-3.2.0.tgz";
        sha512 = "SbbZ+Kqj/XIunvIAgUZRlqd6CGQYq71tRRbXR92Za8J/R3Yh4Av+TWENiSiEgnlwckYLyP0YZQWVfyNC0dzLaA==";
      };
    };
    "split2-4.1.0" = {
      name = "split2";
      packageName = "split2";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split2/-/split2-4.1.0.tgz";
        sha512 = "VBiJxFkxiXRlUIeyMQi8s4hgvKCSjtknJv/LVYbrgALPwf5zSKmEwV9Lst25AkvMDnvxODugjdl6KZgwKM1WYQ==";
      };
    };
    "thread-stream-2.1.0" = {
      name = "thread-stream";
      packageName = "thread-stream";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thread-stream/-/thread-stream-2.1.0.tgz";
        sha512 = "5+Pf2Ya31CsZyIPYYkhINzdTZ3guL+jHq7D8lkBybgGcSQIKDbid3NJku3SpCKeE/gACWAccDA/rH2B6doC5aA==";
      };
    };
    "tiny-lru-8.0.2" = {
      name = "tiny-lru";
      packageName = "tiny-lru";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-lru/-/tiny-lru-8.0.2.tgz";
        sha512 = "ApGvZ6vVvTNdsmt676grvCkUCGwzG9IqXma5Z07xJgiC5L7akUMof5U8G2JTI9Rz/ovtVhJBlY6mNhEvtjzOIg==";
      };
    };
    "typescript-4.8.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.8.2.tgz";
        sha512 = "C0I1UsrrDHo2fYI5oaCGbSejwX4ch+9Y5jTQELvovfmFkK3HHSZJB8MSJcWLmCUBzQBchCrZ9rMRV6GuNrvGtw==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "example-node-nix";
    packageName = "example-node-nix";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      sources."@fastify/ajv-compiler-3.2.0"
      sources."@fastify/deepmerge-1.1.0"
      sources."@fastify/error-3.0.0"
      sources."@fastify/fast-json-stringify-compiler-4.1.0"
      sources."@tsconfig/node16-1.0.3"
      sources."@tsconfig/node16-strictest-1.0.3"
      sources."@types/node-18.7.14"
      sources."abort-controller-3.0.0"
      sources."abstract-logging-2.0.1"
      sources."ajv-8.11.0"
      sources."ajv-formats-2.1.1"
      sources."archy-1.0.0"
      sources."atomic-sleep-1.0.0"
      sources."avvio-8.2.0"
      sources."cookie-0.5.0"
      sources."debug-4.3.4"
      sources."event-target-shim-5.0.1"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stringify-5.2.0"
      sources."fast-redact-3.1.2"
      sources."fast-uri-2.1.0"
      sources."fastify-4.5.3"
      sources."fastq-1.13.0"
      sources."find-my-way-7.0.1"
      sources."forwarded-0.2.0"
      sources."ipaddr.js-1.9.1"
      sources."json-schema-traverse-1.0.0"
      sources."light-my-request-5.5.1"
      sources."lru-cache-6.0.0"
      sources."ms-2.1.2"
      sources."on-exit-leak-free-2.1.0"
      sources."pino-8.4.2"
      sources."pino-abstract-transport-1.0.0"
      sources."pino-std-serializers-6.0.0"
      sources."process-warning-2.0.0"
      sources."proxy-addr-2.0.7"
      sources."punycode-2.1.1"
      sources."quick-format-unescaped-4.0.4"
      sources."readable-stream-4.1.0"
      sources."real-require-0.2.0"
      sources."require-from-string-2.0.2"
      sources."ret-0.2.2"
      sources."reusify-1.0.4"
      sources."rfdc-1.3.0"
      sources."safe-regex2-2.0.0"
      sources."safe-stable-stringify-2.3.1"
      sources."secure-json-parse-2.5.0"
      sources."semver-7.3.7"
      sources."set-cookie-parser-2.5.1"
      sources."sonic-boom-3.2.0"
      sources."split2-4.1.0"
      sources."thread-stream-2.1.0"
      sources."tiny-lru-8.0.2"
      sources."typescript-4.8.2"
      sources."uri-js-4.4.1"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
